name: Java CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: QAProject
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build project with Maven
        run: |
          mvn clean install -DskipTests=false \
            -Dspring.datasource.url=jdbc:mysql://127.0.0.1:3306/QAProject?useSSL=false&allowPublicKeyRetrieval=true \
            -Dspring.datasource.username=root \
            -Dspring.datasource.password=root

      - name: Run unit tests
        run: |
          mvn test \
            -Dspring.datasource.url=jdbc:mysql://127.0.0.1:3306/QAProject?useSSL=false&allowPublicKeyRetrieval=true \
            -Dspring.datasource.username=root \
            -Dspring.datasource.password=root

      - name: Run REST Assured API tests
        run: |
          mvn verify \
            -Dspring.datasource.url=jdbc:mysql://127.0.0.1:3306/QAProject?useSSL=false&allowPublicKeyRetrieval=true \
            -Dspring.datasource.username=root \
            -Dspring.datasource.password=root
