name: Java CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Java
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'

      # Step 3: Build project with Maven
      - name: Build project
        run: mvn clean install -DskipTests=false

      # Step 4: Run unit tests
      - name: Run unit tests
        run: mvn test

      # Step 5: Run REST Assured API tests
      - name: Run API tests
        run: mvn verify
