name: Java CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'   # <- added

      - name: Build project
        run: mvn clean install -DskipTests=false

      - name: Run unit tests
        run: mvn test

      - name: Run REST Assured API tests
        run: mvn verify
