- name: Build project
  run: |
    mvn clean install -DskipTests=false \
      -Dspring.datasource.url=jdbc:mysql://127.0.0.1:3306/QAProject?useSSL=false&allowPublicKeyRetrieval=true \
      -Dspring.datasource.username=root \
      -Dspring.datasource.password=K@v!09171234

- name: Run unit tests
  run: |
    mvn test \
      -Dspring.datasource.url=jdbc:mysql://127.0.0.1:3306/QAProject?useSSL=false&allowPublicKeyRetrieval=true \
      -Dspring.datasource.username=root \
      -Dspring.datasource.password=K@v!09171234

- name: Run REST Assured API tests
  run: |
    mvn verify \
      -Dspring.datasource.url=jdbc:mysql://127.0.0.1:3306/QAProject?useSSL=false&allowPublicKeyRetrieval=true \
      -Dspring.datasource.username=root \
      -Dspring.datasource.password=K@v!09171234
